### ISSUE TITLE
Parameter estimation

### ISSUE THREAD

**Issue by anhackastro** [cschreib/fastpp#11]
I am trying to fit a galaxy SED using fast but the code seems to not be able to estimate some parameter values correctly. For example the value which I get for Av is always equal to maximum or minimum possible value for Av. I attaching all the relevant files here.

[fastfits.zip](https://github.com/cschreib/fastpp/files/2986634/fastfits.zip)

**Comment by cschreib** [comment]
Thanks for reporting the problem. This seems to be an issue with the Milky Way attenuation curve. Switching to Calzetti fixes the problem. I'll see if I can fix the bug with the MW attenuation though, because it should be working.

(by the way, a million Monte Carlo simulations is way too much, you would get the same results with just a thousand simulations)

**Comment by cschreib** [comment]
I have found the issue. If you pull the code from github and re-compile, it should work. Be sure to delete any ```.grid``` cache file in the directory you are working on, otherwise the code will not re-generate the model fluxes and the bug will still appear.

**Comment by anhackastro** [comment]
I will try that. Thanks for the help!

**Comment by anhackastro** [comment]
After pulling the code and recompiling ,I am still not able to get the correct parameter estimates(even when I use calzetti dust curve). I am getting a negative lmass and ltau is ramaining fixed at the initial value (its value is not varying). I am facing this problem with all the the different galaxies I tried to fit. I am attaching an  example here containing the relevant input and output files. This same data has been used in previous publication with FAST IDL code and it gave a good result (see for ex http://adsabs.harvard.edu/abs/2014MNRAS.445.3263H) I dont have idl and hence can only use the C++ version. Kindly help me with this.
[fastfits.zip](https://github.com/cschreib/fastpp/files/2996467/fastfits.zip)

**Comment by cschreib** [comment]
* For the negative ```lmass```. With the default zero point of ```AB_ZEROPOINT=23.9``` (in the FAST parameter file), the input fluxes must be in micro Jansky. It does not appear to be the case in your catalog, as your fluxes have values of order ```1e-10``` which is way too low. In fact, based on the magnitudes given in the paper, I can see your values are a factor ```1e-12``` too low. I don't know how you got your fluxes, but you must have done something wrong. If you add 12 to your negative ```lmass```, you will find a mass of ```6e9```, which is similar to the value quoted in the paper.

* For ```ltau```. Your grid only has four values of ```ltau```, so it's not too surprising that the code only uses one value. If you decrease the step size for ```ltau``` you will see that higher values are sometimes chosen in the Monte Carlo simulation, but it's just rare. This only means that your galaxy has an old stellar population with little on-going SFR, and that your photometry strongly disfavors higher values of ```ltau```. There's no bug here, it's just what the data tells you.
